# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: amundsen-search
  version: "4.2.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/amundsen-search-${{ version }}.tar.gz
  sha256: 4d6cf0e15b27a628880e44097fe9318f28fae4eb7683a0974e3c147e35e3f32d

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }},<4.0
    - elasticsearch ==7.13.3
    - elasticsearch-dsl ==7.4.0
    - amundsen-common >=0.27.0
    - attrs >=19.1.0
    - boto3 >=1.17.23
    - click >=8.1.7
    - flasgger >=0.9.5
    - flask >=2.2.5
    - flask-restful >=0.3.9
    - flask-cors >=3.0.10
    - itsdangerous >=2.1.2
    - jinja2 >=3.1.2
    - jsonschema >=3.0.1,<4.0
    - marshmallow >=3.0,<=3.6
    - marshmallow3-annotations >=1.1.0
    - pytz >=2021.1
    - requests >=2.25.0
    - requests-aws4auth >=1.1.0
    - statsd >=3.2.1
    - typing >=3.6.4
    - werkzeug >=3.0.1
    - wheel >=0.38.1

tests:
  - python:
      imports:
        - search_service
      pip_check: true
      python_version: ${{ python_min }}.*
about:
  summary: Search Service for Amundsen
  license: Apache-2.0
  license_file:
    - LICENSE
  homepage: https://github.com/amundsen-io/amundsen/tree/main/search

extra:
  recipe-maintainers:
    - rxm7706
